# Port
server.port=8585

# Context Path
server.servlet.context-path=/workintech

# Actuator endpointlerini aç
management.endpoints.web.exposure.include=*

# Info endpoint bilgileri
info.app.name=Developer API
info.app.description=Spring Boot Developer Project
info.app.version=1.0.0